default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shopify_app_development

test:
  <<: *default
  database: shopify_app_test

production:
  <<: *default
  database: shopify_app_production
  username: shopify_app
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>